website/models.py
from . import db


class Medicine(db.Model):
    """
        This class is extended from the attribute db so it has all the functionality
        of the SQLAlchemy.
        This class used to create objects for database entry
        And to retrieve data from database

        :param NULL: None

        :type NULL: None

        :return: None

        :rtype: None.
    """
    product_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False, unique=True)
    company_name = db.Column(db.Text, nullable=False)
    price = db.Column(db.Float, nullable=False)
    description = db.Column(db.Text)
    image = db.Column(db.Text)
    quantity = db.Column(db.Integer, nullable=False)
    side_effects = db.Column(db.Text)

    # Create A String
    def __repr__(self):
        return '<Name %r>' % self.name

website/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


# search field in search page
class SearchForm(FlaskForm):
    """
        This class holds the search bar text field, where the input is entered

        :param NULL: None

        :type NULL: None

        :return: None

        :rtype: None
    """

    search_input = StringField("Search", validators=[DataRequired()], id="search_auto")

website/__init__.py
from flask import Flask, render_template
from os import environ
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    """
        Returns the flask app after configuring it with secret key and database
        registers views via blueprint
        handles any missing or non existing route by displaying a custom error page

        :param NULL: None

        :type NULL: None

        :return: None

        :rtype: None
    """

    app = Flask(__name__)

    # Secret Key!
    app.config['SECRET_KEY'] = "Life Pharma"

    # URI of database
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'

    db.init_app(app)

    # 404 custom error page
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("error_404.html"), 404

    # Register views in app blueprint
    from .views import views
    app.register_blueprint(views, url_prefix='/')

    from .models import Medicine

    return app

website/views.py
import cv2
import json
import pickle
import os as os
import pytesseract
from PIL import Image
from .models import Medicine
from .forms import SearchForm
from flask import Flask, Blueprint, render_template, request, Response


pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
UPLOAD_FOLDER = "website/static/img"

views = Blueprint('views', __name__)


# autocomplete/ show suggestion in the search box while typing
@views.route('/_autocomplete_search', methods=['GET'])
def autocomplete_search():
    """
        This method is used to suggest users the product name depending on the input.

        :param Null: None.

        :type Null: None.

        :return: products which start with the characters typed by user.

        :rtype: json.
    """

    items = []

    all_item = Medicine.query.order_by(Medicine.name)

    for item in all_item:
        items.append(item.name)

    return Response(json.dumps(items), mimetype='application/json')


# search page
@views.route('/search.html', methods=['GET', 'POST'])
def search_page(sent_item=None):
    """
        This method allows the user to search, and according to the input, the
        the page would show if deatils of the product if it exists in database,
        otherwise will show item not found.

        :param sent_item: Its a text string.


        :type sent_item: String.

        :return: search option view.

        :rtype: html.
    """

    form = SearchForm(request.form)

    if sent_item:
        searched_item = sent_item
    else:
        searched_item = None

    if request.method == "POST":
        searched_item = form.search_input.data
        form.search_input.data = ''

    if searched_item is not None:
        all_item = Medicine.query.filter(Medicine.name.startswith(searched_item)).all()

    else:
        all_item = Medicine.query.filter_by(name=searched_item).all()

    return render_template('search.html', form=form, searched_item=searched_item, items=all_item)


@views.route('/camera.html', methods=['GET', 'POST'])
def camera_page():
    """
        This method is used to capture image, and after that send it to get predicted.

        :param Null: None.

        :type Null: None.

        :return: image capture view.

        :rtype: html.
    """
    if request.method == "POST":

        if os.path.exists("website/static/img/temp.jpg"):
            return upload(file="website/static/img/temp.jpg")
            
        else:
            return render_template("error_404.html")

    return render_template('camera.html')


# save the image as a picture
@views.route('/_camera_image', methods=['POST'])
def image_from_camera():

    """
        This method is used to save the image that is taken in the camera page

        :param NULL: None

        :type NULL: None

        :return: returns response as saved

        :rtype: Response.
    """
    image_file = request.files['image']  # get the image
    image_file.save('%s/%s' % ('website/static/img', 'temp.jpg'))

    return Response("saved")





# Predict function to predict
def predict(img_path):
    """
        This method is used to predict the Text consists in a Image.

        :param img_path: It's a path of the image from where have to predict.

        :type img_path: String.

        :return: String. Predicted String

        :rtype: String.
    """
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # img = cv2.medianBlur(img,5)
    text = pytesseract.image_to_string(img)
    #print(text)
    return text


# dumping last predict info to pickle
def dump(text):
    """
        This method is used to dump  the last predicted Text to a pickle file.

        :param text: Its a text string.

        :type text: String.

        :return: It will return nothing.

        :rtype: None.
    """
    list = []
    list = op()
    list.append(text)
    with open('last_search.pkl', 'wb') as f:
        pickle.dump(list, f)
        f.close()


# open the pickle file
def op():
    """
        This method is used to open the pickle file named last_search.pkl. Load file to a list and return it
        for further searching processing.

        :param Null: None.

        :type Null: None.

        :return: It will return  a list file.

        :rtype: list.
    """

    with open('last_search.pkl', 'rb') as f:
        mylist = pickle.load(f)
        f.close()
    return mylist


# Refer to search page
@views.route('/_search')
def sarch_page():
    """
        This method is used to get the search page. In here, last search text will be retrive and pass to search. 

        :param Null: None.

        :type request: None.

        :return: this method returns a search html page.

        :rtype: HttpResponse.
    """
    list = op()
    last_serch = list[len(list) - 1]
    return search_page(sent_item=last_serch)


# upload funtion for uploading and saving Image
@views.route('/Upload_Image', methods=["GET", "POST"])
def upload(file=None):
    """
        This method is used to get the image from httpResponse and feedback the HttpResponse with predicted text.
        This method saved the image in a folder and send the location to predict function.After getting text return from
        predict function, it wll show the test buy returning at html page.

        :param file: it's a HttpResponse from user..

        :type request: HttpResponse.

        :return: this method returns a html page.It returns a page where it has three options, Upload Image
          ,Prediction  and Search option.

        :rtype: HttpResponse.
    """
    is_sent = False
    if not file:
        if request.method == "POST":
            image_file = request.files["image"]
            if image_file:
                image_location = os.path.join(
                    UPLOAD_FOLDER, image_file.filename
                )
                image_file.save(image_location)
                is_sent = True
                #print(image_location)
    else:
        image_location = file
        is_sent = True

    if is_sent:
        pred = predict(image_location)
        dump(pred)
        return render_template("Upload_Image.html", prediction=pred, image_loc=image_file.filename)

    return render_template("Upload_Image.html", prediction=0)

website/templates/Base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<!--{% block css%}
    {% endblock css%} -->

    <title>{% block title %}Life Pharma{% endblock title %}</title>

    {% include 'Nevbar.html' %}

  </head>

  <body>


    {%block content%}
    {%endblock content%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

website/templates/Nevbar.html
<nav class="navbar fixed-top p-3  navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand">Life Pharma</span>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Searched</a>
        </li>
      </ul>
    </div>
<!--
    {% if logged_in %}

       <div class="dropdown-container">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; text-decoration:underline; padding:5">{{name}}</a>
         <ul class="dropdown-menu dropdown-menu-end">
           <li><button class="dropdown-item" type="button"><i class="far fa-user" style="padding: 5px"></i>Profile</button></li>
           <li><hr class="dropdown-divider"></li>
           <li><button class="dropdown-item" type="button"><i class="fas fa-sign-out-alt" style="padding: 5px"></i>Sign Out</button></li>
         </ul>
       </div>

    {% else: %}

      <div class="text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      </div>

    {% endif %}
-->
  </div>
</nav>

website/templates/Upload_Image.html
{% extends 'Base.html' %}

{%block content%}
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">



    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/Upload_Image.css"  rel="stylesheet">
  </head>

  <body class="text-center"; style="background-color: #bcd0c7">
    <form class="form-Upload_Image" method = post enctype=multipart/form-data>
      <h1 class="h3 mb-3 font-weight-normal">Please Upload Image </h1>
      <input type="file" id="image" name= "image" class="form-control"  required autofocus>
        <br>
      <button class="btn btn-lg btn-primary btn-dark" type="submit" name ="submit_button" value ="Do something">Predict</button>
        <button type="button" class="btn btn-lg btn-primary btn-dark" type ="submit">Remove</button>
        <br>
        <br>
        {%if image_loc%}
        <img class="mb-4" src="static/{{image_loc}}" alt="" width="256" height="256">
            <h1 class="h3 mb-3 font-weight-normal">Prediction: {{ prediction}} </h1>
        {% endif %}
    <br>

    </form>
  <a class="btn btn-lg btn-primary btn-dark" id ="search" href="{{ url_for('views.sarch_page') }}">Search</a>

  </body>


{%endblock content%}

website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    {% block css%}
    {% endblock css%}

    <title>{% block title %}Life Pharma{% endblock title %}</title>



  </head>

  <body>

    {% include 'navbar.html' %}

    {%block content%}
    {%endblock content%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

website/templates/camera.html
{% extends 'base.html' %}


{% block css%}
    <link href="{{ url_for( 'static', filename='css/camera.css' ) }}" rel="stylesheet">
{% endblock css%}

{%block content%}

    <video id="camera" autoplay></video>
    <button class="btn btn-primary btn-lg col-4" id="snap" onclick="sendImagefromCanvas()"><i class="fas fa-camera fa-2x"></i></button>
    <form method="post">
        <button class="btn btn-primary btn-lg col-2" id="predict" ><i class="fas fa-capsules"></i>  Predict</button>
    </form>




    <script>

        let photo = document.getElementById("camera");

        //create a canvas to grab an image for upload

        let imageCanvas = document.createElement('canvas');
        let imageCtx = imageCanvas.getContext("2d");

        //Add file blob to a form and post
        function postFile(file) {
            let formdata = new FormData();
            formdata.append("image", file);
            let xhr = new XMLHttpRequest();
            xhr.open('POST', "{{ url_for('views.image_from_camera') }}", true);
            xhr.onload = function () {
                if (this.status === 200)
                    console.log(this.response);
                else
                    console.error(xhr);
            };
            xhr.send(formdata);
        }

        //Get the image from the canvas
        function sendImagefromCanvas() {

            //Make sure the canvas is set to the current video size
            imageCanvas.width = photo.videoWidth;
            imageCanvas.height = photo.videoHeight;

            imageCtx.drawImage(photo, 0, 0, photo.videoWidth, photo.videoHeight);

            //Convert the canvas to blob and post the file
            imageCanvas.toBlob(postFile, 'static/img/jpeg');
        }

        //Take a picture on click
    //    camera.onclick = function() {
    //        console.log('click');
    //        sendImagefromCanvas();
    //     };

        window.onload = function () {

            //Get camera video
            navigator.mediaDevices.getUserMedia({video: {width: 852, height: 480}, audio: false})
                .then(stream => {
                    photo.srcObject = stream;
                })
                .catch(err => {
                    console.log('navigator.getUserMedia error: ', err)
                });

        };

    </script>

{%endblock content%}

website/templates/error_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 Error</title>
</head>
<body>

  <br/>
  <br/>
  <center>
    <h1>404 Error</h1>
    <p>Page Not Found</p>

  </center>

</body>
</html>

website/templates/index.html
<h1> hello world!</h1>

website/templates/navbar.html
<nav class="navbar fixed-top p-3  navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <span class="navbar-brand">Life Pharma</span>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.search_page') }}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.camera_page') }}">Camera</a>
        </li>
      </ul>
    </div>

    {% if not logged_in %}

       <div class="dropdown-container">
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white; text-decoration:underline; padding:5">{{name}}</a>
         <ul class="dropdown-menu dropdown-menu-end">
           <li><button class="dropdown-item" type="button"><i class="far fa-user" style="padding: 5px"></i>Profile</button></li>
           <li><hr class="dropdown-divider"></li>
           <li><button class="dropdown-item" type="button"><i class="fas fa-sign-out-alt" style="padding: 5px"></i>Sign Out</button></li>
         </ul>
       </div>

    {% else: %}

      <div class="text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      </div>

    {% endif %}

  </div>
</nav>

website/templates/search.html
{% extends 'base.html' %}


{% block css%}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <link href="{{ url_for( 'static', filename='css/search.css' ) }}" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock css%}


{%block content%}

{% if searched_item %}

  <br/><br/><br/>
  <br/><br/><br/>
  <br/><br/><br/>

  <center>
    <h1 class="head-tag">You searched for {{ searched_item }} </h1>
    <br/>
    <h2 class="head-tag-detail">Details:</h2>
    <br/>

    {% if items %}

      <table class="table table-sm table-striped table-hover">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Company</th>
            <th scope="col">Price/Pack</th>
            <th scope="col">Stock</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
            <tr>
              <td>{{item.name}}</td>
              <td>{{item.company_name}}</td>
              <td>{{item.price}}</td>
              <td>{% if item.quantity > 0 %}
                    In stock
                  {% else %}
                    Out of stock
                  {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

    {% else %}

      <h1 class="head-tag">Item not found in database</h1>
    {% endif %}
</center>

{% else %}

  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.search_input(class="search_input", placeholder="Search...") }}
        <button type="submit" class="search_icon"><i class="fas fa-search"></i></button>

      </form>
    </div>
  </div>


{% endif %}

<script>
    $(function() {
        $.ajax({
            url: '{{ url_for("views.autocomplete_search") }}'
            }).done(function (data){
                $('#search_auto').autocomplete({
                    source: data,
                    minLength: 1
                });
            });
        });
</script>

{%endblock content%}